PREFIX hcm: <https://w3id.org/hcmo/ontology/hcm#>
PREFIX hcm-bio: <https://w3id.org/hcmo/ontology/hcm/bio#>

SELECT ?enclosure (GROUP_CONCAT(STR(?subject); separator=", ") AS ?subjects)
WHERE {
  ?enclosure a hcm:MonitoredEnclosure .
  OPTIONAL {
    ?assignment a hcm-bio:HousingAssignment ;
                hcm-bio:assignedToEnclosure ?enclosure .
    ?subject a hcm-bio:Subject ;
             hcm-bio:hasHousingAssignment ?assignment .
  }
}
GROUP BY ?enclosure
ORDER BY ?enclosure
