PREFIX hcm: <https://w3id.org/hcmo/ontology/hcm#>

SELECT ?enclosure
WHERE {
  ?enclosure a hcm:MonitoredEnclosure .
  FILTER NOT EXISTS { ?enclosure hcm:hasDimensions ?dimensions }
}
ORDER BY ?enclosure
