PREFIX hcm: <https://w3id.org/hcmo/ontology/hcm#>
PREFIX hcm-tech: <https://w3id.org/hcmo/ontology/hcm/tech#>

SELECT ?enclosure ?sensor ?property
WHERE {
  ?enclosure a hcm:MonitoredEnclosure ;
             hcm-tech:monitoredBy ?sensor .
  OPTIONAL { ?sensor hcm-tech:captures ?property }
}
ORDER BY ?enclosure ?sensor ?property
