PREFIX hcm: <https://w3id.org/hcmo/ontology/hcm#>
PREFIX hcm-obs: <https://w3id.org/hcmo/ontology/hcm/obs#>
PREFIX sosa: <http://www.w3.org/ns/sosa/>
PREFIX time: <http://www.w3.org/2006/time#>

SELECT DISTINCT ?enclosure ?observation ?duration ?unit ?condition
WHERE {
  ?observation a hcm-obs:BehaviorObservation ;
               hcm-obs:occursIn ?enclosure ;
               hcm-obs:hasCondition ?condition ;
               sosa:phenomenonTime ?interval .
  ?enclosure a hcm:MonitoredEnclosure .
  ?interval time:numericDuration ?duration ;
            time:unitType ?unit .
  VALUES (?unit ?minimum) {
    (time:unitHour 24)
    (time:unitDay 1)
  }
  FILTER (?duration >= ?minimum)
}
ORDER BY ?enclosure ?observation
