#!/usr/bin/env python3
"""Build the HCMO instance graph for the REAL Tecniplast DVC(R) cohort-7623 export.

Input (real data, see ``datasets/real/README.md``):
  * ``Cohort7623_events.csv``                       cage lifecycle events
  * ``Cohort7623_animal_loc__index_smoothed.csv``   1-min smoothed activation index

Output: ``examples/systems/dvc-tecniplast.ttl``

Modelling decisions (all documented in ``hcmo-mapping.tsv`` and ``README.md``):
  * one DVC cage  -> hcm:MonitoredEnclosure (rack + position as schema:Place)
  * the animals of a cage -> one hcm-bio:ExperimentalGroup per cage, because the
    export carries no individual identity (no RFID) and no housing density;
    the group is housed through a time-bounded hcm-bio:HousingAssignment that
    spans the cage's first INSERTED event to the end of the export
  * INSERTED / REMOVED events -> hcm:OperationalStatusRecord validity intervals
    generated by an hcm:OperationalAssessment (rack-controller cage detection)
  * each 1-min activation-index bin -> sosa:Observation with the cage group as
    feature of interest and an hcm-obs:QuantityValue result (unit:PERCENT);
    HCMO 0.3.0 has no activity-specific observation subtype for a group-level
    numeric result, so the generic SOSA class is used and the gap is recorded
  * only ACTIVITY_CAGES x ACTIVITY_MINUTES bins are materialised to keep the
    evaluation graph small; the full export is referenced as hcm-tech:TimeSeries

Deterministic: the same inputs always yield byte-identical Turtle.
"""
from __future__ import annotations

import csv
import sys
from datetime import datetime, timedelta, timezone
from decimal import Decimal
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[3]
sys.path.insert(0, str(ROOT / "tooling"))

from rdflib import RDF, RDFS, Literal  # noqa: E402

from hcmo_instance import (  # noqa: E402
    DCTERMS,
    HCM,
    HCM_OBS,
    HCM_TECH,
    PROV,
    SCHEMA,
    SOSA,
    TIME,
    UNIT,
    InstanceGraph,
    xsd_datetime,
)

REAL = HERE / "datasets" / "real"
EVENTS = REAL / "Cohort7623_events.csv"
INDEX = REAL / "Cohort7623_animal_loc__index_smoothed.csv"
OUT = ROOT / "examples" / "systems" / "dvc-tecniplast.ttl"
BASE = "https://w3id.org/hcmo/id/eval/dvc-tecniplast/"

GROUP = "B6_M"
# Activity bins are materialised for these cages over this window (local time,
# UTC-04:00 as in the export). All 24 cages are online from 10:28 onwards.
ACTIVITY_CAGES = ["B6_M_12_3401", "B6_M_12_3402", "B6_M_12_3403", "B6_M_12_3404"]
ACTIVITY_START = datetime(2025, 10, 14, 11, 0, tzinfo=timezone(timedelta(hours=-4)))
ACTIVITY_MINUTES = 180

# Tecniplast GM500 mouse IVC (the DVC-monitored cage type): external
# 391 x 199 x 160 mm, floor area 501 cm2 (vendor product sheet; see README).
CAGE_DIMENSIONS_CM = (Decimal("19.9"), Decimal("39.1"), Decimal("16.0"))


def parse_ts(text: str) -> datetime:
    # "2025-10-14T10:16:00.000-0400"
    return datetime.strptime(text, "%Y-%m-%dT%H:%M:%S.%f%z")


def slug(cage: str) -> str:
    return cage.lower().replace("_", "-")


def load_events() -> dict[str, list[dict]]:
    by_cage: dict[str, list[dict]] = {}
    with EVENTS.open(encoding="utf-8", newline="") as handle:
        for row in csv.DictReader(handle):
            by_cage.setdefault(row["cage"], []).append(row)
    for rows in by_cage.values():
        rows.sort(key=lambda r: r["timestamp"])
    return by_cage


def load_activity() -> tuple[list[str], list[dict]]:
    with INDEX.open(encoding="utf-8", newline="") as handle:
        reader = csv.DictReader(handle)
        rows = list(reader)
        cages = [c for c in reader.fieldnames if c.startswith(f"{GROUP}_12_")]
    return cages, rows


def main() -> int:
    events = load_events()
    cage_columns, activity_rows = load_activity()
    ig = InstanceGraph(BASE, "dvc")

    export_end = max(parse_ts(r["timestamp"]) for rows in events.values() for r in rows)
    export_start = min(parse_ts(r["timestamp"]) for rows in events.values() for r in rows)

    # --- provenance of the data -------------------------------------------
    ig.dataset_note(
        "cohort-7623-export",
        label="Real DVC Analytics export, cohort 7623, group B6_M",
        description=(
            "Real Tecniplast DVC export contributed for HCMO validation: 24 cages on one rack, "
            "14 days at 1-minute resolution. Only four cages and a three-hour window of "
            "activation-index bins are materialised as observations; the full files are "
            "referenced as time series."
        ),
        source="docs/hcm-systems/systems/DVC_Tecniplast/datasets/real/README.md",
        real_data=True,
    )

    # --- technical chain ----------------------------------------------------
    vendor = ig.typed("tecniplast", SCHEMA.Organization, label="Tecniplast S.p.A.")
    rack_controller = ig.hardware("rack-aaaa-controller", label="DVC rack AAAA controller")
    ig.add(rack_controller, SCHEMA.manufacturer, vendor)
    analytics = ig.software("dvc-analytics", label="DVC Analytics (cloud)", runs_on=rack_controller)
    ig.add(analytics, RDFS.comment, Literal(
        "Proprietary cloud software that acquires the 4 Hz electrode stream and derives the "
        "smoothed activation/locomotion index exported here; the derivation algorithm is not public."
    ))
    ig.add(rack_controller, HCM_TECH.communicatesWith, analytics)

    activation_index = ig.observable_property(
        "activation-index",
        "smoothed activation / locomotion index (share of active electrodes per bin)",
    )

    index_series = ig.time_series(
        "cohort-7623-activation-index-series",
        label="Cohort 7623 smoothed activation index, 1-min bins, 24 cages",
        file_format="text/csv",
        storage_path="docs/hcm-systems/systems/DVC_Tecniplast/datasets/real/Cohort7623_animal_loc__index_smoothed.csv",
        comment="Wide-format export: one row per 1-minute bin, one column per cage plus cohort AVG/SEM/QRT/SAMPLES aggregates.",
    )
    ig.add(index_series, PROV.wasAttributedTo, analytics)
    events_series = ig.time_series(
        "cohort-7623-events-series",
        label="Cohort 7623 cage lifecycle event log",
        file_format="text/csv",
        storage_path="docs/hcm-systems/systems/DVC_Tecniplast/datasets/real/Cohort7623_events.csv",
    )
    ig.add(events_series, PROV.wasAttributedTo, analytics)

    detection = ig.typed(
        "rack-aaaa-cage-detection",
        HCM.OperationalAssessment, PROV.Activity,
        label="DVC rack AAAA cage-presence detection (INSERTED/REMOVED events)",
    )
    ig.add(detection, PROV.wasAssociatedWith, rack_controller)

    cohort = ig.group(
        "cohort-7623-b6-m",
        label="Cohort 7623 group B6_M",
        comment=(
            "Export group label 'B6_M' (C57BL/6 males per the contributor). Strain and sex are "
            "not attributable to individual subjects because the export carries no animal identity."
        ),
    )

    # --- one enclosure + cage group per DVC cage ---------------------------
    cage_groups = {}
    boards = {}
    for cage in sorted(events):
        s = slug(cage)
        rows = events[cage]
        inserted = [r for r in rows if r["event"] == "INSERTED"]
        dims = ig.dimensions(f"cage-{s}-dimensions", *CAGE_DIMENSIONS_CM)
        enclosure = ig.enclosure(
            f"cage-{s}",
            label=f"DVC cage {cage}",
            identifier=cage,
            dimensions=dims,
            manufacturer="Tecniplast S.p.A.",
            comment="Tecniplast GM500 individually ventilated mouse cage monitored by a DVC capacitive board; dimensions from the vendor product sheet, not from the export.",
        )
        ig.add(enclosure, DCTERMS.type, Literal("individually ventilated cage"))
        if inserted:
            last_place = inserted[-1]
            place = ig.typed(
                f"rack-{last_place['rack'].lower()}-position-{last_place['position'].lower()}",
                SCHEMA.Place,
                label=f"DVC rack {last_place['rack']} position {last_place['position']}",
            )
            ig.add(enclosure, HCM.locatedIn, place)
        else:
            # Real-data quirk: this cage streams data but the event log holds
            # no INSERTED row, so its rack position is unknown.
            ig.add(enclosure, RDFS.comment, Literal(
                "The event log contains no INSERTED/REMOVED event for this cage although the index "
                "file streams data for it; rack position and operational status are therefore unknown."
            ))

        board = ig.sensor(
            f"board-{s}",
            label=f"DVC capacitive electrode board under cage {cage}",
            identifier=f"DVC-board-{cage}",
            technology="capacitance (12-electrode array)",
            sensor_type="electrical capacitance proximity sensor",
            sampling_rate_hz=4,
            installed_in=enclosure,
            captures=[activation_index],
        )
        ig.add(board, HCM_TECH.communicatesWith, rack_controller)
        boards[cage] = board

        group = ig.group(
            f"cage-group-{s}",
            label=f"Animals housed in DVC cage {cage}",
            comment="Cage-level cohort: the DVC export identifies cages, not animals, and does not state housing density.",
        )
        ig.add(group, SCHEMA.isPartOf, cohort)
        cage_groups[cage] = group
        first_event = parse_ts((inserted or rows)[0]["timestamp"])
        ig.housing(
            f"housing-{s}",
            holder=group,
            enclosure=enclosure,
            start=first_event,
            end=export_end + timedelta(minutes=1),
        )

        # Operational status: online between INSERTED and REMOVED events.
        # Each event starts a new state; every state lasts until the next
        # event or the end of the export.
        transitions = sorted(
            (parse_ts(r["timestamp"]), r["event"] == "INSERTED")
            for r in rows
            if r["event"] in ("INSERTED", "REMOVED")
        )
        closed = []
        for index, (start, online) in enumerate(transitions):
            end = transitions[index + 1][0] if index + 1 < len(transitions) else export_end + timedelta(minutes=1)
            if end > start:
                closed.append((start, end, online))
        for index, (start, end, online) in enumerate(closed, start=1):
            record = ig.typed(f"status-{s}-{index}", HCM.OperationalStatusRecord)
            ig.add(record, HCM.hasOperationalStatusValue, Literal(online))
            ig.add(record, TIME.hasTime, ig.interval(f"status-{s}-{index}-validity", start, end, duration_unit=TIME.unitMinute))
            ig.add(record, PROV.wasGeneratedBy, detection)
            ig.add(enclosure, HCM.hasOperationalStatusRecord, record)
        if closed:
            ig.add(detection, HCM.assessesEnclosure, enclosure)

    # --- activation-index observations (real values) ----------------------
    window_end = ACTIVITY_START + timedelta(minutes=ACTIVITY_MINUTES)
    instants: dict[datetime, object] = {}

    def instant_for(when: datetime):
        if when not in instants:
            instants[when] = ig.instant(f"t-{when.strftime('%Y%m%dT%H%M')}", when)
        return instants[when]

    n_obs = 0
    for row in activity_rows:
        when = parse_ts(row[f"{GROUP}_TIMESTAMP"])
        if not (ACTIVITY_START <= when < window_end):
            continue
        bin_end = when + timedelta(minutes=1)
        stamp = when.strftime("%Y%m%dT%H%M")
        interval = None
        for cage in ACTIVITY_CAGES:
            value = row[cage]
            if value == "":
                continue
            if interval is None:
                interval = ig.typed(f"bin-{stamp}", TIME.Interval)
                ig.add(interval, TIME.hasBeginning, instant_for(when))
                ig.add(interval, TIME.hasEnd, instant_for(bin_end))
            s = slug(cage)
            result = ig.result_quantity(f"result-{s}-{stamp}", Decimal(value).quantize(Decimal("0.001")), UNIT.PERCENT)
            ig.observation(
                f"obs-{s}-{stamp}",
                cls=SOSA.Observation,
                feature=cage_groups[cage],
                sensor=boards[cage],
                prop=activation_index,
                result=result,
                phenomenon_time=interval,
                occurs_in=ig.iri(f"cage-{s}"),
            )
            n_obs += 1

    header = (
        "# GENERATED by docs/hcm-systems/systems/DVC_Tecniplast/generate_hcmo_instance.py — DO NOT EDIT\n"
        "# HCMO instance graph derived from the REAL Tecniplast DVC cohort-7623 export.\n"
        f"# Cage lifecycle: {len(cage_groups)} cages from {export_start.isoformat()} to {export_end.isoformat()}.\n"
        f"# Activation-index observations: {n_obs} one-minute bins for {len(ACTIVITY_CAGES)} cages "
        f"from {ACTIVITY_START.isoformat()} ({ACTIVITY_MINUTES} min).\n"
    )
    ig.serialize(OUT, header)
    print(f"wrote {OUT.relative_to(ROOT)}: {len(ig.g)} triples, {n_obs} observations, {len(cage_groups)} cages")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
