#!/usr/bin/env python3
"""Build the HCMO instance graph for the Tecniplast DVC(R) coverage example.

Two cohorts are combined and every node states where it comes from. Both are
MOCK data: no value in this graph was recorded from animals.

  * MOCK cohort 7623, group B6_M (``datasets/real/`` -- historical folder name;
    the files are a mock export in the DVC Analytics export schema): 24 cages
    on rack AAAA, lifecycle events and 1-min smoothed activation-index bins.
  * SYNTHETIC cohort B6_F (``datasets/mock/mock_B6_F_*``): 8 cages on rack
    BBBB generated by ``datasets/mock/generate_dvc_traces.py`` so that the
    scenario also contains cages of females.

Mock experimental metadata (requested to make the scenario realistic; NOT part
of the exports) is added on top of both cohorts:

  * light programme: lights OFF 19:00-07:00 (12:12), stated as hcm-env:LightCycle
  * rack environment: temperature and relative humidity readings of the rack
    environmental monitor (REM) every 15 min, with room targets 22 degC / 50 %
  * housing: 2 mice per cage, C57BL/6J, males in B6_M and females in B6_F,
    with mock dates of birth; the cage-level ExperimentalGroup keeps its members
  * husbandry: cage change every Wednesday between 10:00 and 11:00
  * hardware/software: GM500 IVC cages, DVC Analytics 3.5

Modelling decisions (see ``hcmo-mapping.tsv`` and ``README.md``):
  * one DVC cage -> hcm:MonitoredEnclosure (rack + position as schema:Place,
    the rack itself as an hcm:Enclosure that carries the environment profile)
  * the animals of a cage -> hcm-bio:ExperimentalGroup with two hcm-bio:Subject
    members; the cage-level activation index keeps the GROUP as feature of
    interest because the sensor cannot attribute activity to an individual
  * INSERTED / REMOVED events -> hcm:OperationalStatusRecord validity intervals
  * each activation-index bin -> sosa:Observation + hcm-obs:QuantityValue (%)
  * REM readings -> hcm-obs:EnvironmentObservation about the rack
  * cage changes -> prov:Activity with a bounded interval, prov:used the cage

Deterministic: the same inputs always yield byte-identical Turtle.
"""
from __future__ import annotations

import csv
import random
import sys
from datetime import date, datetime, timedelta, timezone
from decimal import Decimal
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[3]
sys.path.insert(0, str(ROOT / "tooling"))

from rdflib import RDF, RDFS, Literal  # noqa: E402

from hcmo_instance import (  # noqa: E402
    DCTERMS,
    HCM,
    HCM_BIO,
    HCM_ENV,
    HCM_OBS,
    HCM_TECH,
    PROV,
    SCHEMA,
    SOSA,
    TIME,
    UNIT,
    InstanceGraph,
)

REAL = HERE / "datasets" / "real"
MOCK = HERE / "datasets" / "mock"
OUT = ROOT / "examples" / "systems" / "dvc-tecniplast.ttl"
BASE = "https://w3id.org/hcmo/id/eval/dvc-tecniplast/"
TZ = timezone(timedelta(hours=-4))

COHORTS = [
    {
        "group": "B6_M", "sex": "male", "kind": "mock cohort 7623", "rack": "AAAA",
        "events": REAL / "Cohort7623_events.csv",
        "index": REAL / "Cohort7623_animal_loc__index_smoothed.csv",
        "activity_cages": ["B6_M_12_3401", "B6_M_12_3402", "B6_M_12_3403", "B6_M_12_3404"],
        "activity_start": datetime(2025, 10, 14, 11, 0, tzinfo=TZ),
        "activity_minutes": 180,
    },
    {
        "group": "B6_F", "sex": "female", "kind": "synthetic cohort", "rack": "BBBB",
        "events": MOCK / "mock_B6_F_events.csv",
        "index": MOCK / "mock_B6_F_animal_loc__index_smoothed.csv",
        "activity_cages": ["B6_F_12_3400", "B6_F_12_3401"],
        "activity_start": datetime(2025, 10, 14, 18, 0, tzinfo=TZ),
        "activity_minutes": 120,
    },
]
MICE_PER_CAGE = 2
STRAIN = "C57BL/6J"
DARK_START = "19:00:00"
CAGE_CHANGE_WEEKDAY = 2  # Wednesday
CAGE_CHANGE_HOURS = (10, 11)
ENV_INTERVAL_MIN = 15
# Tecniplast GM500 mouse IVC: external 391 x 199 x 160 mm, floor 501 cm2 (product sheet).
CAGE_DIMENSIONS_CM = (Decimal("19.9"), Decimal("39.1"), Decimal("16.0"))


def parse_ts(text: str) -> datetime:
    return datetime.strptime(text, "%Y-%m-%dT%H:%M:%S.%f%z")


def slug(cage: str) -> str:
    return cage.lower().replace("_", "-")


def load_events(path: Path) -> dict[str, list[dict]]:
    by_cage: dict[str, list[dict]] = {}
    with path.open(encoding="utf-8", newline="") as handle:
        for row in csv.DictReader(handle):
            by_cage.setdefault(row["cage"], []).append(row)
    for rows in by_cage.values():
        rows.sort(key=lambda r: r["timestamp"])
    return by_cage


def load_index(path: Path) -> list[dict]:
    with path.open(encoding="utf-8", newline="") as handle:
        return list(csv.DictReader(handle))


def wednesdays(start: datetime, end: datetime):
    day = start.date()
    while day <= end.date():
        if day.weekday() == CAGE_CHANGE_WEEKDAY:
            yield day
        day += timedelta(days=1)


def main() -> int:
    ig = InstanceGraph(BASE, "dvc")
    rng = random.Random(7623)

    # --- provenance --------------------------------------------------------
    ig.dataset_note(
        "cohort-7623-export",
        label="Mock DVC Analytics export, cohort 7623, group B6_M (rack AAAA)",
        description=(
            "Mock export in the Tecniplast DVC Analytics export schema (not recorded from animals): 24 cages "
            "on one rack, 14 days at 1-minute resolution. Four cages and a three-hour window of activation-index bins are materialised."
        ),
        source="docs/hcm-systems/systems/DVC_Tecniplast/datasets/real/README.md",
        real_data=False,
    )
    ig.dataset_note(
        "cohort-b6-f-mock-export",
        label="Synthetic DVC export, group B6_F (rack BBBB)",
        description=(
            "Schema-faithful synthetic DVC export (8 cages, 3 days) generated by datasets/mock/generate_dvc_traces.py "
            "so that the scenario also holds cages of females. Two cages and a two-hour window are materialised."
        ),
        source="docs/hcm-systems/systems/DVC_Tecniplast/datasets/mock/README.md",
        real_data=False,
    )
    metadata_note = ig.dataset_note(
        "mock-experimental-metadata",
        label="Mock experimental metadata added to both cohorts",
        description=(
            "Light programme (dark 19:00-07:00), rack temperature/humidity readings, two C57BL/6J mice per cage "
            "with mock dates of birth, and Wednesday 10:00-11:00 cage changes are NOT in the exports; they are "
            "realistic assumptions stated to complete the scenario."
        ),
        source="docs/hcm-systems/systems/DVC_Tecniplast/README.md",
        real_data=False,
    )

    # --- technical chain -----------------------------------------------------
    vendor = ig.typed("tecniplast", SCHEMA.Organization, label="Tecniplast S.p.A.")
    analytics = ig.software("dvc-analytics", label="DVC Analytics (cloud)", version="3.5")
    ig.add(analytics, RDFS.comment, Literal(
        "Proprietary cloud software that acquires the 4 Hz electrode stream and derives the smoothed "
        "activation/locomotion index exported here; the derivation algorithm is not public."
    ))
    activation_index = ig.observable_property(
        "activation-index", "smoothed activation / locomotion index (share of active electrodes per bin)"
    )
    p_temp = ig.environmental_property("rack-air-temperature", "rack air temperature (REM)")
    p_rh = ig.environmental_property("rack-relative-humidity", "rack relative humidity (REM)")

    light_cycle = ig.light_cycle("light-cycle-12-12", dark_start=DARK_START, dark_hours=12, light_hours=12,
                                 label="Facility light programme: lights off 19:00-07:00 (mock metadata)")
    spec_temp = ig.measurement_spec("room-temperature-target", p_temp, Decimal("22.0"), UNIT.DEG_C, "Room temperature target 22 degC")
    spec_rh = ig.measurement_spec("room-humidity-target", p_rh, Decimal("50.0"), UNIT.PERCENT, "Room relative-humidity target 50 %")
    profile = ig.environment_profile("holding-room-profile", label="Holding room environment profile (mock metadata)",
                                     light_cycle=light_cycle, specs=[spec_temp, spec_rh])
    ig.add(profile, PROV.wasDerivedFrom, metadata_note)

    detection_by_rack, rem_by_rack, rack_enclosure = {}, {}, {}
    n_obs = n_env = n_changes = 0
    subject_counter = 0

    for cohort in COHORTS:
        group_label, rack_id = cohort["group"], cohort["rack"]
        events = load_events(cohort["events"])
        index_rows = load_index(cohort["index"])
        export_start = min(parse_ts(r["timestamp"]) for rows in events.values() for r in rows)
        export_end = max(parse_ts(r["timestamp"]) for rows in events.values() for r in rows) + timedelta(minutes=1)
        kind = cohort["kind"]

        rack = ig.typed(f"rack-{rack_id.lower()}", HCM.Enclosure, label=f"DVC rack {rack_id}",
                        comment="Rack holding the DVC cages; the rack environmental monitor (REM) observes its air, so the rack carries the environment profile.")
        ig.add(rack, HCM.hasEnclosureIdentifier, Literal(rack_id))
        ig.add(rack, HCM_ENV.hasEnvironment, profile)
        rack_enclosure[rack_id] = rack
        controller = ig.hardware(f"rack-{rack_id.lower()}-controller", label=f"DVC rack {rack_id} controller")
        ig.add(controller, SCHEMA.manufacturer, vendor)
        ig.add(controller, HCM_TECH.communicatesWith, analytics)
        ig.add(analytics, HCM_TECH.runsOn, controller)
        rem = ig.sensor(f"rem-{rack_id.lower()}", label=f"DVC rack environmental monitor (REM), rack {rack_id}",
                        identifier=f"DVC-REM-{rack_id}", technology="temperature and relative-humidity sensor",
                        captures=[p_temp, p_rh])
        ig.add(rem, HCM_TECH.communicatesWith, controller)
        rem_by_rack[rack_id] = rem
        detection = ig.typed(f"rack-{rack_id.lower()}-cage-detection", HCM.OperationalAssessment, PROV.Activity,
                             label=f"DVC rack {rack_id} cage-presence detection (INSERTED/REMOVED events)")
        ig.add(detection, PROV.wasAssociatedWith, controller)
        detection_by_rack[rack_id] = detection

        for suffix in ("activation-index-series", "events-series"):
            series = ig.time_series(
                f"{group_label.lower().replace('_', '-')}-{suffix}",
                label=f"{group_label} {'smoothed activation index, 1-min bins' if 'index' in suffix else 'cage lifecycle event log'}",
                file_format="text/csv",
                storage_path=str((cohort["index"] if "index" in suffix else cohort["events"]).relative_to(ROOT).as_posix()),
            )
            ig.add(series, PROV.wasAttributedTo, analytics)

        cohort_group = ig.group(
            f"cohort-{group_label.lower().replace('_', '-')}",
            label=f"Cohort group {group_label} ({kind})",
            comment=f"Export group label '{group_label}': {STRAIN} {cohort['sex']}s, {MICE_PER_CAGE} per cage (housing metadata is mock).",
        )

        cage_groups, boards = {}, {}
        for cage in sorted(events):
            s = slug(cage)
            rows = events[cage]
            inserted = [r for r in rows if r["event"] == "INSERTED"]
            dims = ig.dimensions(f"cage-{s}-dimensions", *CAGE_DIMENSIONS_CM)
            enclosure = ig.enclosure(
                f"cage-{s}", label=f"DVC cage {cage}", identifier=cage, dimensions=dims, manufacturer="Tecniplast S.p.A.",
                comment="Tecniplast GM500 individually ventilated mouse cage monitored by a DVC capacitive board; dimensions from the vendor product sheet.",
            )
            ig.add(enclosure, DCTERMS.type, Literal("GM500 individually ventilated cage"))
            ig.add(enclosure, HCM_ENV.hasEnvironment, profile)
            ig.add(enclosure, HCM.hasEnrichment, ig.enrichment(f"cage-{s}-nesting", "nesting material", f"Nesting material in cage {cage} (mock metadata)"))
            ig.add(enclosure, HCM_TECH.monitoredBy, rem)
            if inserted:
                last = inserted[-1]
                place = ig.typed(f"rack-{last['rack'].lower()}-position-{last['position'].lower()}", SCHEMA.Place,
                                 label=f"DVC rack {last['rack']} position {last['position']}")
                ig.add(place, SCHEMA.isPartOf, rack)
                ig.add(enclosure, HCM.locatedIn, place)
            else:
                ig.add(enclosure, RDFS.comment, Literal(
                    "The event log contains no INSERTED/REMOVED event for this cage although the index file streams data "
                    "for it; rack position and operational status are therefore unknown."))
            board = ig.sensor(f"board-{s}", label=f"DVC capacitive electrode board under cage {cage}", identifier=f"DVC-board-{cage}",
                              technology="capacitance (12-electrode array)", sensor_type="electrical capacitance proximity sensor",
                              sampling_rate_hz=4, installed_in=enclosure, captures=[activation_index])
            ig.add(board, HCM_TECH.communicatesWith, controller)
            boards[cage] = board

            group = ig.group(f"cage-group-{s}", label=f"Animals housed in DVC cage {cage}",
                             comment=f"Cage-level cohort of {MICE_PER_CAGE} {STRAIN} {cohort['sex']}s (mock housing metadata); the DVC signal is attributed to the cage, not to an individual.")
            ig.add(group, SCHEMA.isPartOf, cohort_group)
            cage_groups[cage] = group
            first_event = parse_ts((inserted or rows)[0]["timestamp"])
            ig.housing(f"housing-{s}", holder=group, enclosure=enclosure, start=first_event, end=export_end)
            for member in range(1, MICE_PER_CAGE + 1):
                subject_counter += 1
                dob = date(2025, 6, 20) + timedelta(days=rng.randint(0, 14))
                subject = ig.subject(f"mouse-{s}-{member}", label=f"Mouse {member} of cage {cage} (mock metadata)", species="Mus musculus",
                                     strain=STRAIN, sex=cohort["sex"], date_of_birth=dob.isoformat(), group=group)
                ig.add(subject, DCTERMS.identifier, Literal(f"{cage}-{member}"))
                ig.add(subject, PROV.wasDerivedFrom, metadata_note)
                ig.housing(f"housing-{s}-{member}", holder=subject, enclosure=enclosure, start=first_event, end=export_end)

            # operational status from INSERTED / REMOVED transitions
            transitions = sorted((parse_ts(r["timestamp"]), r["event"] == "INSERTED") for r in rows if r["event"] in ("INSERTED", "REMOVED"))
            closed = []
            for i, (start, online) in enumerate(transitions):
                end = transitions[i + 1][0] if i + 1 < len(transitions) else export_end
                if end > start:
                    closed.append((start, end, online))
            for i, (start, end, online) in enumerate(closed, start=1):
                record = ig.typed(f"status-{s}-{i}", HCM.OperationalStatusRecord)
                ig.add(record, HCM.hasOperationalStatusValue, Literal(online))
                ig.add(record, TIME.hasTime, ig.interval(f"status-{s}-{i}-validity", start, end, duration_unit=TIME.unitMinute))
                ig.add(record, PROV.wasGeneratedBy, detection)
                ig.add(enclosure, HCM.hasOperationalStatusRecord, record)
            if closed:
                ig.add(detection, HCM.assessesEnclosure, enclosure)

            # mock cage changes: every Wednesday 10:00-11:00 within the export
            for day in wednesdays(export_start, export_end):
                start = datetime(day.year, day.month, day.day, CAGE_CHANGE_HOURS[0], 0, tzinfo=TZ)
                if not (export_start <= start <= export_end):
                    continue
                change = ig.typed(f"cage-change-{s}-{day.isoformat()}", PROV.Activity,
                                  label=f"Cage change of {cage} on {day.isoformat()} (mock husbandry schedule)")
                ig.add(change, PROV.used, enclosure)
                ig.add(change, TIME.hasTime, ig.interval(f"cage-change-{s}-{day.isoformat()}-time", start, start + timedelta(hours=1)))
                ig.add(change, PROV.wasDerivedFrom, metadata_note)
                n_changes += 1

        # activation-index observations
        window_start = cohort["activity_start"]
        window_end = window_start + timedelta(minutes=cohort["activity_minutes"])
        instants = {}

        def instant_for(when: datetime):
            if when not in instants:
                instants[when] = ig.instant(f"t-{when.strftime('%Y%m%dT%H%M')}", when)
            return instants[when]

        for row in index_rows:
            when = parse_ts(row[f"{group_label}_TIMESTAMP"])
            if not (window_start <= when < window_end):
                continue
            stamp = when.strftime("%Y%m%dT%H%M")
            interval = None
            for cage in cohort["activity_cages"]:
                value = row[cage]
                if value == "":
                    continue
                if interval is None:
                    interval = ig.typed(f"bin-{stamp}", TIME.Interval)
                    ig.add(interval, TIME.hasBeginning, instant_for(when))
                    ig.add(interval, TIME.hasEnd, instant_for(when + timedelta(minutes=1)))
                s = slug(cage)
                result = ig.result_quantity(f"result-{s}-{stamp}", Decimal(value).quantize(Decimal("0.001")), UNIT.PERCENT)
                ig.observation(f"obs-{s}-{stamp}", cls=SOSA.Observation, feature=cage_groups[cage], sensor=boards[cage], prop=activation_index,
                               result=result, phenomenon_time=interval, occurs_in=ig.iri(f"cage-{s}"))
                n_obs += 1

        # REM readings (mock) every 15 min over the same window
        when = window_start
        while when < window_end:
            stamp = when.strftime("%Y%m%dT%H%M")
            interval = ig.typed(f"env-bin-{rack_id.lower()}-{stamp}", TIME.Interval)
            ig.add(interval, TIME.hasBeginning, instant_for(when))
            ig.add(interval, TIME.hasEnd, instant_for(when + timedelta(minutes=ENV_INTERVAL_MIN)))
            temp = Decimal(str(round(rng.uniform(21.6, 22.6), 1)))
            rh = Decimal(str(round(rng.uniform(45.0, 55.0), 1)))
            for key, prop, value, unit in (("temp", p_temp, temp, UNIT.DEG_C), ("rh", p_rh, rh, UNIT.PERCENT)):
                result = ig.result_quantity(f"res-{key}-{rack_id.lower()}-{stamp}", value, unit)
                obs = ig.observation(f"obs-{key}-{rack_id.lower()}-{stamp}", cls=HCM_OBS.EnvironmentObservation, feature=rack, sensor=rem,
                                     prop=prop, result=result, phenomenon_time=interval, occurs_in=rack)
                ig.add(obs, PROV.wasDerivedFrom, metadata_note)
                n_env += 1
            when += timedelta(minutes=ENV_INTERVAL_MIN)

    header = (
        "# GENERATED by docs/hcm-systems/systems/DVC_Tecniplast/generate_hcmo_instance.py — DO NOT EDIT\n"
        "# HCMO instance graph for the Tecniplast DVC: MOCK cohort 7623 (B6_M, 24 cages) plus a SYNTHETIC female\n"
        "# cohort (B6_F, 8 cages) and MOCK experimental metadata (light programme, REM readings, 2 mice per cage,\n"
        "# Wednesday cage changes). Every mock node is linked to the mock-experimental-metadata dataset note.\n"
        f"# {n_obs} activation-index observations, {n_env} REM environment observations, {subject_counter} subjects, {n_changes} cage changes.\n"
    )
    ig.serialize(OUT, header)
    print(f"wrote {OUT.relative_to(ROOT)}: {len(ig.g)} triples, {n_obs} activity + {n_env} environment observations, {subject_counter} subjects, {n_changes} cage changes")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
