#!/usr/bin/env python3
"""Build BioPortal-facing HCMO v2 clean artifacts.

The v2 clean files are generated from ontology/v2/modules except
hcm-placeholders.ttl, so unresolved UNKNOWN:/placeholder terms stay out of the
BioPortal submission while the review draft remains available.
"""
from __future__ import annotations

import os
import sys
from pathlib import Path

from rdflib import Graph, Namespace
from rdflib.compare import isomorphic, to_canonical_graph

if os.environ.get("PYTHONHASHSEED") != "0":
    os.environ["PYTHONHASHSEED"] = "0"
    os.execv(sys.executable, [sys.executable] + sys.argv)

ROOT = Path(__file__).resolve().parent.parent
V2 = ROOT / "ontology" / "v2"

MODULES = [
    V2 / "modules" / "hcm-core.ttl",
    V2 / "modules" / "hcm-bio.ttl",
    V2 / "modules" / "hcm-env.ttl",
    V2 / "modules" / "hcm-obs.ttl",
    V2 / "modules" / "hcm-tech.ttl",
]


def bind_prefixes(g: Graph) -> None:
    g.bind("hcm", Namespace("https://w3id.org/hcmo/ontology/hcm#"), replace=True)
    g.bind("hcm-bio", Namespace("https://w3id.org/hcmo/ontology/hcm/bio#"), replace=True)
    g.bind("hcm-env", Namespace("https://w3id.org/hcmo/ontology/hcm/env#"), replace=True)
    g.bind("hcm-obs", Namespace("https://w3id.org/hcmo/ontology/hcm/obs#"), replace=True)
    g.bind("hcm-tech", Namespace("https://w3id.org/hcmo/ontology/hcm/tech#"), replace=True)
    g.bind("owl", Namespace("http://www.w3.org/2002/07/owl#"), replace=True)
    g.bind("rdfs", Namespace("http://www.w3.org/2000/01/rdf-schema#"), replace=True)
    g.bind("dc", Namespace("http://purl.org/dc/elements/1.1/"), replace=True)
    g.bind("dcterms", Namespace("http://purl.org/dc/terms/"), replace=True)
    g.bind("schema", Namespace("https://schema.org/"), replace=True)
    g.bind("sosa", Namespace("http://www.w3.org/ns/sosa/"), replace=True)
    g.bind("time", Namespace("http://www.w3.org/2006/time#"), replace=True)
    g.bind("semts", Namespace("https://w3id.org/semts/ontology/120#"), replace=True)
    g.bind("mod", Namespace("https://w3id.org/mod#"), replace=True)


def write_text(path: Path, text: str) -> None:
    path.write_text(text, encoding="utf-8", newline="\n")


def main() -> int:
    merged = Graph()
    for module in MODULES:
        merged.parse(module, format="turtle")

    canon = Graph()
    for triple in sorted(to_canonical_graph(merged), key=lambda t: (str(t[0]), str(t[1]), str(t[2]))):
        canon.add(triple)
    bind_prefixes(canon)

    ttl_path = V2 / "hcmo-v2-merged-clean.ttl"
    owl_path = V2 / "hcmo-v2-merged-clean.owl"

    write_text(
        ttl_path,
        "# DO NOT EDIT - GENERATED by tooling/build_v2_clean.py from ontology/v2/modules, excluding hcm-placeholders.ttl.\n"
        + canon.serialize(format="turtle"),
    )
    write_owl = True
    if owl_path.exists():
        try:
            existing_owl = Graph().parse(owl_path)
            write_owl = not isomorphic(existing_owl, canon)
        except Exception:
            write_owl = True

    if write_owl:
        owl_xml = canon.serialize(format="pretty-xml")
        marker = "<!-- DO NOT EDIT - GENERATED by tooling/build_v2_clean.py from ontology/v2/modules, excluding hcm-placeholders.ttl. -->\n"
        if owl_xml.startswith("<?xml"):
            first_line, rest = owl_xml.split("\n", 1)
            owl_xml = first_line + "\n" + marker + rest
        else:
            owl_xml = marker + owl_xml
        write_text(owl_path, owl_xml)

    print("Build complete:")
    print(f"  {ttl_path.relative_to(ROOT)} ({len(canon)} triples)")
    print(f"  {owl_path.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
