#!/usr/bin/env python3
"""Multi-system coverage and ontology-quality evaluation for HCMO.

Reads ``evaluation/multi-system.yaml`` and produces deterministic Markdown
reports under ``evaluation/reports/``:

  coverage.md               native-concept -> HCMO coverage per system and module
  competency-questions.md   cross-system competency questions with exact answers
  shacl.md                  SHACL shape inventory, conformance, probes, negatives
  ontology-metrics.md       per-module term/axiom counts and reused external terms
  reasoner.md               HermiT result (only with --reason; needs Java)

The same checks that back the reports are exposed through ``check_all`` for the
CI gate in ``tooling/validate.py`` (SHACL conformance of every system graph,
negative probes, exact competency answers).

Usage:
  python tooling/evaluate.py                # write reports
  python tooling/evaluate.py --reason       # also run HermiT and write reasoner.md
  python tooling/evaluate.py --print-answers  # print current CQ rows as YAML
"""
from __future__ import annotations

import argparse
import csv
import json
import sys
from collections import Counter, defaultdict
from pathlib import Path

import yaml
from rdflib import OWL, RDF, RDFS, Graph, Literal, Namespace, URIRef
from pyshacl import validate as shacl_validate

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "tooling"))

HCM = Namespace("https://w3id.org/hcmo/ontology/hcm#")
HCM_BIO = Namespace("https://w3id.org/hcmo/ontology/hcm/bio#")
SH = Namespace("http://www.w3.org/ns/shacl#")
QUDT = Namespace("http://qudt.org/schema/qudt/")
TIME = Namespace("http://www.w3.org/2006/time#")
SOSA = Namespace("http://www.w3.org/ns/sosa/")

MODULE_NAMESPACES = {
    "core": "https://w3id.org/hcmo/ontology/hcm#",
    "bio": "https://w3id.org/hcmo/ontology/hcm/bio#",
    "env": "https://w3id.org/hcmo/ontology/hcm/env#",
    "obs": "https://w3id.org/hcmo/ontology/hcm/obs#",
    "tech": "https://w3id.org/hcmo/ontology/hcm/tech#",
}
MODULE_FILES = {
    "core": "ontology/modules/hcm-core.ttl",
    "bio": "ontology/modules/hcm-bio.ttl",
    "env": "ontology/modules/hcm-env.ttl",
    "obs": "ontology/modules/hcm-obs.ttl",
    "tech": "ontology/modules/hcm-tech.ttl",
    "compat": "ontology/modules/hcm-compat.ttl",
    "upper": "ontology/modules/external-upper.ttl",
}
EXTERNAL_PREFIXES = {
    "BFO": "http://purl.obolibrary.org/obo/BFO_",
    "IAO": "http://purl.obolibrary.org/obo/IAO_",
    "sosa": "http://www.w3.org/ns/sosa/",
    "semts": "https://w3id.org/semts/ontology#",
    "time": "http://www.w3.org/2006/time#",
    "prov": "http://www.w3.org/ns/prov#",
    "qudt": "http://qudt.org/schema/qudt/",
    "unit": "http://qudt.org/vocab/unit/",
    "schema": "https://schema.org/",
    "dcterms": "http://purl.org/dc/terms/",
    "obi": "http://purl.obolibrary.org/obo/OBI_",
    "stato": "http://purl.obolibrary.org/obo/STATO_",
}
MAPPING_KINDS = ("hcmo", "external", "partial", "not-covered")
GENERATED = "<!-- GENERATED by tooling/evaluate.py — DO NOT EDIT; regenerate with `python tooling/evaluate.py` -->\n"


# --------------------------------------------------------------------------- io
def load_yaml(path: Path) -> dict:
    return yaml.safe_load(path.read_text(encoding="utf-8"))


def load_manifest() -> dict:
    return load_yaml(ROOT / "hcmo.yaml")


def load_index() -> dict:
    return load_yaml(ROOT / "evaluation" / "multi-system.yaml")


def ontology_graph(manifest: dict) -> Graph:
    g = Graph()
    for rel in manifest["modules"]:
        g.parse(ROOT / rel, format="turtle")
    return g


def write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8", newline="\n")


def curie(iri: str) -> str:
    prefixes = {**{f"hcm-{k}" if k != "core" else "hcm": v for k, v in MODULE_NAMESPACES.items()}, **EXTERNAL_PREFIXES, "sh": str(SH)}
    for prefix, namespace in prefixes.items():
        if iri.startswith(namespace):
            return f"{prefix}:{iri[len(namespace):]}"
    return iri


def md_table(headers: list[str], rows: list[list]) -> str:
    out = ["| " + " | ".join(headers) + " |", "|" + "|".join(" --- " for _ in headers) + "|"]
    for row in rows:
        out.append("| " + " | ".join(str(cell) for cell in row) + " |")
    return "\n".join(out) + "\n"


# ---------------------------------------------------------------- coverage
def read_mapping(path: Path) -> list[dict[str, str]]:
    with path.open(encoding="utf-8", newline="") as handle:
        rows = list(csv.DictReader(handle, delimiter="\t"))
    required = {"native_concept", "source", "description", "module", "mapping", "hcmo_target", "note"}
    for row in rows:
        missing = required - set(row)
        if missing:
            raise ValueError(f"{path}: missing columns {sorted(missing)}")
        if row["mapping"] not in MAPPING_KINDS:
            raise ValueError(f"{path}: invalid mapping kind {row['mapping']!r} for {row['native_concept']!r}")
        if row["module"] not in (*MODULE_NAMESPACES, "—"):
            raise ValueError(f"{path}: invalid module {row['module']!r} for {row['native_concept']!r}")
    return rows


def wilson_interval(k: int, n: int, z: float = 1.959964) -> tuple[float, float]:
    """Wilson score 95 % interval for a proportion k/n, in percent."""
    if n == 0:
        return 0.0, 0.0
    p = k / n
    denom = 1 + z * z / n
    centre = (p + z * z / (2 * n)) / denom
    half = z * ((p * (1 - p) / n + z * z / (4 * n * n)) ** 0.5) / denom
    return 100.0 * (centre - half), 100.0 * (centre + half)


def pct_ci(k: int, n: int) -> str:
    low, high = wilson_interval(k, n)
    return f"{k}/{n} = {100.0 * k / n:.0f}% [{low:.0f}–{high:.0f}]" if n else "—"


def coverage_stats(rows: list[dict[str, str]]) -> dict:
    kinds = Counter(row["mapping"] for row in rows)
    total = len(rows)
    mapped = kinds["hcmo"] + kinds["external"] + kinds["partial"]
    per_module = defaultdict(Counter)
    for row in rows:
        per_module[row["module"]][row["mapping"]] += 1
    return {
        "total": total,
        "kinds": kinds,
        "native": kinds["hcmo"],
        "native_or_external": kinds["hcmo"] + kinds["external"],
        "mapped": mapped,
        "pct_mapped": 100.0 * mapped / total if total else 0.0,
        "pct_native": 100.0 * kinds["hcmo"] / total if total else 0.0,
        "per_module": per_module,
    }


def instance_stats(graph: Graph) -> dict:
    """Instances per HCMO class and per reused external class."""
    counts = Counter()
    for _, _, cls in graph.triples((None, RDF.type, None)):
        counts[str(cls)] += 1
    return counts


def coverage_report(index: dict, graphs: dict[str, Graph]) -> str:
    lines = [GENERATED, "# Multi-system coverage of HCMO 0.3.0\n"]
    lines.append(
        "Coverage is computed from each system's mapping table "
        "(`hcmo-mapping.tsv`): every native concept or export variable is mapped to "
        "an HCMO term (**hcmo**), expressed through a reused external term in the "
        "HCMO pattern (**external**), expressed only partially or through a generic "
        "pattern (**partial**), or deliberately left uncovered (**not-covered**).\n"
    )
    lines.append(
        "> **Read these figures with their limits.** (1) Every export is **synthetic**: "
        "no system graph derives from recorded animal data. (2) Each mapping table was "
        "written by a **single annotator**, who for most systems also designed the "
        "synthetic export from the system's documentation; the review status column "
        "tracks independent review by each system's developers. (3) The intervals are "
        "Wilson 95 % score intervals over the native concepts of one system; they "
        "reflect the small number of concepts, not disagreement between annotators, "
        "and the differences between systems are descriptive, not tested. "
        "**HCMO-native** is the headline figure; the cumulative columns show how much "
        "more becomes expressible when reused external terms and generic or lossy "
        "patterns are accepted.\n"
    )
    lines.append("## Systems\n")
    rows = []
    totals = Counter()
    for system in index["systems"]:
        stats = coverage_stats(read_mapping(ROOT / system["mapping"]))
        n = stats["total"]
        totals.update({"n": n, "native": stats["native"], "native_or_external": stats["native_or_external"],
                       "mapped": stats["mapped"], "not": stats["kinds"]["not-covered"]})
        review = system.get("mapping_review", {}).get("status", "not reviewed")
        rows.append([
            system["name"], system["data"], review, len(graphs[system["id"]]), n,
            pct_ci(stats["native"], n), pct_ci(stats["native_or_external"], n),
            pct_ci(stats["mapped"], n), stats["kinds"]["not-covered"],
        ])
    rows.append([
        "**All systems (pooled)**", "", "", "", totals["n"],
        pct_ci(totals["native"], totals["n"]), pct_ci(totals["native_or_external"], totals["n"]),
        pct_ci(totals["mapped"], totals["n"]), totals["not"],
    ])
    lines.append(md_table(
        ["System", "Data", "Mapping review", "Triples", "Native concepts",
         "HCMO-native [95% CI]", "+ external (cumulative)", "+ partial (cumulative)", "Not covered"],
        rows,
    ))
    lines.append("\n## Systems × HCMO modules (HCMO-native / expressible at all / assigned to the module)\n")
    module_rows = []
    for system in index["systems"]:
        stats = coverage_stats(read_mapping(ROOT / system["mapping"]))
        row = [system["id"]]
        for module in MODULE_NAMESPACES:
            counts = stats["per_module"].get(module, Counter())
            total = sum(counts.values())
            mapped = counts["hcmo"] + counts["external"] + counts["partial"]
            row.append("—" if total == 0 else f"{counts['hcmo']} / {mapped} / {total}")
        row.append(str(sum(stats["per_module"].get("—", Counter()).values())))
        module_rows.append(row)
    lines.append(md_table(["System", *MODULE_NAMESPACES, "out of scope"], module_rows))
    lines.append("\n## HCMO modules, pooled over all systems\n")
    pooled = defaultdict(Counter)
    for system in index["systems"]:
        for row in read_mapping(ROOT / system["mapping"]):
            pooled[row["module"]][row["mapping"]] += 1
    pooled_rows = []
    for module in MODULE_NAMESPACES:
        counts = pooled.get(module, Counter())
        n = sum(counts.values())
        pooled_rows.append([
            module, n, pct_ci(counts["hcmo"], n),
            pct_ci(counts["hcmo"] + counts["external"] + counts["partial"], n), counts["not-covered"],
        ])
    lines.append(md_table(["Module", "Native concepts", "HCMO-native [95% CI]", "Expressible at all [95% CI]", "Not covered"], pooled_rows))
    lines.append(f"\nOut of scope (no module): {sum(pooled.get('—', Counter()).values())} concepts.\n")
    lines.append("\n## Instance inventory per system\n")
    for system in index["systems"]:
        graph = graphs[system["id"]]
        counts = instance_stats(graph)
        lines.append(f"### {system['name']} (`{system['graph']}`)\n")
        inv = sorted(((curie(k), v) for k, v in counts.items()), key=lambda kv: (-kv[1], kv[0]))
        lines.append(md_table(["Class", "Instances"], [[k, v] for k, v in inv]))
        lines.append("")
    lines.append("## Gaps and partial mappings\n")
    for system in index["systems"]:
        rows = [r for r in read_mapping(ROOT / system["mapping"]) if r["mapping"] in ("partial", "not-covered")]
        lines.append(f"### {system['name']}\n")
        lines.append(md_table(
            ["Native concept", "Mapping", "HCMO target", "Note"],
            [[r["native_concept"], r["mapping"], r["hcmo_target"] or "—", r["note"]] for r in rows],
        ))
        lines.append("")
    return "\n".join(lines)


# ------------------------------------------------------------------- SHACL
def canonical_rows(result) -> list[dict[str, str | None]]:
    variables = [str(v) for v in result.vars]
    rows = [{v: (None if row[i] is None else str(row[i])) for i, v in enumerate(variables)} for row in result]
    return sorted(rows, key=lambda row: json.dumps(row, sort_keys=True))


def shacl_run(data: Graph, shapes: Graph, ontology: Graph) -> tuple[bool, int, Graph]:
    conforms, report_graph, _ = shacl_validate(
        data, shacl_graph=shapes, ont_graph=ontology, inference="rdfs", abort_on_first=False, do_owl_imports=False
    )
    if not isinstance(report_graph, Graph):
        raise RuntimeError(f"pySHACL validation failure: {report_graph}")
    violations = len(list(report_graph.subjects(RDF.type, SH.ValidationResult)))
    return conforms, violations, report_graph


def copy_graph(graph: Graph) -> Graph:
    out = Graph()
    for triple in graph:
        out.add(triple)
    return out


def negative_probes(graph: Graph) -> dict[str, Graph]:
    """Injected faults that the standard shapes must reject on this graph."""
    probes: dict[str, Graph] = {}
    # 1. strip the unit from one quantity result
    quantity = next((s for s in sorted(graph.subjects(RDF.type, QUDT.QuantityValue), key=str)), None)
    if quantity is not None:
        probe = copy_graph(graph)
        probe.remove((quantity, QUDT.hasUnit, None))
        probes["unitless quantity value"] = probe
    # 2. reverse one housing validity interval
    assignment = next((s for s in sorted(graph.subjects(RDF.type, HCM_BIO.HousingAssignment), key=str)), None)
    if assignment is not None:
        interval = graph.value(assignment, TIME.hasTime)
        begin = graph.value(interval, TIME.hasBeginning)
        end = graph.value(interval, TIME.hasEnd)
        begin_value = graph.value(begin, TIME.inXSDDateTime)
        end_value = graph.value(end, TIME.inXSDDateTime)
        probe = copy_graph(graph)
        probe.set((begin, TIME.inXSDDateTime, end_value))
        probe.set((end, TIME.inXSDDateTime, begin_value))
        probes["reversed housing interval"] = probe
        # 3. overlapping second assignment for the same holder
        holder = graph.value(None, HCM_BIO.hasHousingAssignment, assignment)
        enclosure = graph.value(assignment, HCM_BIO.assignedToEnclosure)
        probe = copy_graph(graph)
        dup = URIRef(str(assignment) + "-overlap-probe")
        probe.add((holder, HCM_BIO.hasHousingAssignment, dup))
        probe.add((dup, RDF.type, HCM_BIO.HousingAssignment))
        probe.add((dup, HCM_BIO.assignedToEnclosure, enclosure))
        probe.add((dup, TIME.hasTime, interval))
        probes["overlapping housing assignment"] = probe
    # 4. detach an enclosure's sensors
    enclosure = next((s for s in sorted(graph.subjects(RDF.type, HCM.MonitoredEnclosure), key=str)), None)
    if enclosure is not None:
        probe = copy_graph(graph)
        probe.remove((enclosure, URIRef("https://w3id.org/hcmo/ontology/hcm/tech#monitoredBy"), None))
        probes["enclosure without sensor"] = probe
    return probes


def shape_inventory(shapes: Graph) -> dict:
    node_shapes = set(shapes.subjects(RDF.type, SH.NodeShape))
    property_shapes = set(shapes.objects(None, SH.property))
    sparql = set(shapes.objects(None, SH.sparql))
    targets = Counter()
    for predicate in (SH.targetClass, SH.targetObjectsOf, SH.targetSubjectsOf):
        targets[curie(str(predicate))] = len(list(shapes.triples((None, predicate, None))))
    constraint_predicates = (SH.minCount, SH.maxCount, SH.datatype, SH["class"], SH.nodeKind, SH.node, SH.minExclusive, SH["or"])
    constraints = sum(len(list(shapes.triples((None, p, None)))) for p in constraint_predicates)
    return {
        "node_shapes": len(node_shapes),
        "property_shapes": len(property_shapes),
        "sparql_constraints": len(sparql),
        "targets": targets,
        "constraints": constraints,
    }


def shacl_evaluation(manifest: dict, index: dict, ontology: Graph, graphs: dict[str, Graph]) -> tuple[bool, list[str], dict]:
    ok = True
    notes: list[str] = []
    shapes = Graph().parse(ROOT / manifest["shapes"], format="turtle")
    results = {"positive": [], "negative": [], "probes": [], "inventory": shape_inventory(shapes)}
    for system in index["systems"]:
        graph = graphs[system["id"]]
        conforms, violations, _ = shacl_run(graph, shapes, ontology)
        results["positive"].append((system["id"], len(graph), conforms, violations))
        if conforms:
            notes.append(f"[OK]   SHACL {system['graph']}: conformant ({len(graph)} triples)")
        else:
            ok = False
            notes.append(f"[FAIL] SHACL {system['graph']}: {violations} violation(s) on a positive system graph")
        for label, probe in negative_probes(graph).items():
            p_conforms, p_violations, _ = shacl_run(probe, shapes, ontology)
            results["probes"].append((system["id"], label, p_conforms, p_violations))
            if p_conforms:
                ok = False
                notes.append(f"[FAIL] SHACL probe '{label}' on {system['id']} conformed")
            else:
                notes.append(f"[OK]   SHACL probe '{label}' on {system['id']}: {p_violations} violation(s)")
    for rel in manifest.get("examples", []):
        if any(token in Path(rel).name.lower() for token in ("edge", "invalid")):
            graph = Graph().parse(ROOT / rel, format="turtle")
            conforms, violations, _ = shacl_run(graph, shapes, ontology)
            results["negative"].append((rel, len(graph), conforms, violations))
    return ok, notes, results


def shacl_report(results: dict) -> str:
    inv = results["inventory"]
    lines = [GENERATED, "# SHACL validation report\n"]
    lines.append("## Shape inventory (`shapes/hcm-shapes.ttl`)\n")
    lines.append(md_table(["Metric", "Value"], [
        ["Node shapes", inv["node_shapes"]],
        ["Property shapes", inv["property_shapes"]],
        ["SPARQL-based constraints", inv["sparql_constraints"]],
        ["Cardinality / datatype / class / node constraints", inv["constraints"]],
        *[[f"Targets via `{k}`", v] for k, v in sorted(inv["targets"].items())],
    ]))
    lines.append("\nValidation runs with the canonical ontology as `ont_graph` and RDFS entailment, exactly as the CI gate does.\n")
    lines.append("## System instance graphs (must conform; any violation is a false positive)\n")
    lines.append(md_table(["System", "Triples", "Conforms", "Violations"], [[s, n, "yes" if c else "no", v] for s, n, c, v in results["positive"]]))
    lines.append("\n## Injected negative probes on the system graphs (must be rejected)\n")
    lines.append(md_table(["System", "Injected fault", "Conforms", "Violations"], [[s, l, "yes" if c else "no", v] for s, l, c, v in results["probes"]]))
    lines.append("\n## Intentionally invalid fixtures from the release manifest\n")
    lines.append(md_table(["Fixture", "Triples", "Conforms", "Violations"], [[s, n, "yes" if c else "no", v] for s, n, c, v in results["negative"]]))
    false_positives = sum(v for _, _, _, v in results["positive"])
    lines.append(f"\nFalse positives on positive data: **{false_positives}**. Every injected fault was detected: **{'yes' if all(not c for _, _, c, _ in results['probes']) else 'no'}**.\n")
    return "\n".join(lines)


# -------------------------------------------------------- competency questions
def evaluation_graph(ontology: Graph, graphs: dict[str, Graph]) -> Graph:
    g = copy_graph(ontology)
    for graph in graphs.values():
        for triple in graph:
            g.add(triple)
    return g


def cq_evaluation(index: dict, union: Graph) -> tuple[bool, list[str], list[dict]]:
    ok = True
    notes: list[str] = []
    cq_index = load_yaml(ROOT / index["queries"]["index"])
    questions = cq_index["questions"]
    discovered = {p.relative_to(ROOT).as_posix() for p in (ROOT / index["queries"]["dir"]).glob("cq-ms-*.rq")}
    indexed = {q["file"] for q in questions}
    if discovered != indexed:
        ok = False
        notes.append(f"[FAIL] cross-system CQ coverage: unindexed={sorted(discovered - indexed)} missing={sorted(indexed - discovered)}")
    results = []
    for question in questions:
        text = (ROOT / question["file"]).read_text(encoding="utf-8")
        actual = canonical_rows(union.query(text))
        expected = sorted(question["expected_answers"], key=lambda r: json.dumps(r, sort_keys=True))
        passed = actual == expected
        if not passed:
            ok = False
            notes.append(
                f"[FAIL] cross-system CQ {question['id']}: expected={json.dumps(expected, sort_keys=True)} actual={json.dumps(actual, sort_keys=True)}"
            )
        else:
            notes.append(f"[OK]   cross-system CQ {question['id']}: {len(actual)} exact answer(s)")
        results.append({**question, "actual": actual, "passed": passed})
    return ok, notes, results


def cq_report(results: list[dict], union: Graph) -> str:
    lines = [GENERATED, "# Cross-system competency questions\n"]
    lines.append(
        f"Executed with rdflib over the union of the canonical ontology and all system instance graphs ({len(union)} triples). "
        "`Status` is *answered* when the complete reviewed answer rows are returned, *answered (empty)* when the reviewed answer is the "
        "verified absence of rows, and *partial* when the question is answerable only for a subset of systems for a documented reason.\n"
    )
    lines.append(
        "> **What a pass means.** The questions and their expected answers were written by the same author who built the graphs, "
        "so a pass shows that the modelling pattern makes each question executable across systems and that nothing has "
        "regressed; it is not an independent test of adequacy. Every value comes from a **synthetic** export, so counts, "
        "means, accuracies and latencies in the answers are properties of the generators, not biological findings.\n"
    )
    rows = []
    for q in results:
        rows.append([q["id"], q["question"], ", ".join(q["modules"]), "cross-system" if q.get("cross_system") else "single-system", f"`{q['file']}`", len(q["actual"]), q["status"] + ("" if q["passed"] else " **(MISMATCH)**")])
    lines.append(md_table(["ID", "Question", "Modules", "Scope", "Query", "Rows", "Status"], rows))
    lines.append("\n## Answers\n")
    for q in results:
        lines.append(f"### {q['id']}\n")
        if q.get("note"):
            lines.append(q["note"] + "\n")
        if q["actual"]:
            headers = list(q["actual"][0].keys())
            lines.append(md_table(headers, [[("" if r[h] is None else curie(r[h]).replace("https://w3id.org/hcmo/id/eval/", "eval:")) for h in headers] for r in q["actual"]]))
        else:
            lines.append("_no rows (verified empty answer)_\n")
        lines.append("")
    return "\n".join(lines)


# ---------------------------------------------------------- ontology metrics
def module_metrics(manifest: dict) -> list[dict]:
    rows = []
    hcmo_namespaces = tuple(MODULE_NAMESPACES.values())
    for module, rel in MODULE_FILES.items():
        g = Graph().parse(ROOT / rel, format="turtle")
        local = lambda s: isinstance(s, URIRef) and str(s).startswith(hcmo_namespaces)  # noqa: E731
        classes = [s for s in g.subjects(RDF.type, OWL.Class) if local(s)]
        obj = [s for s in g.subjects(RDF.type, OWL.ObjectProperty) if local(s)]
        dt = [s for s in g.subjects(RDF.type, OWL.DatatypeProperty) if local(s)]
        deprecated = [s for s in g.subjects(OWL.deprecated, Literal(True)) if local(s)]
        restrictions = len(list(g.subjects(RDF.type, OWL.Restriction)))
        subclass = len([1 for s, _, o in g.triples((None, RDFS.subClassOf, None)) if isinstance(o, URIRef)])
        domains = len(list(g.triples((None, RDFS.domain, None))))
        ranges = len(list(g.triples((None, RDFS.range, None))))
        labels = len([1 for s in set(classes + obj + dt) if g.value(s, RDFS.label)])
        definitions = len([1 for s in set(classes + obj + dt) if g.value(s, RDFS.comment) or g.value(s, URIRef("http://purl.obolibrary.org/obo/IAO_0000115"))])
        external = set()
        for subject, _, obj_term in g:
            for term in (subject, obj_term):
                if isinstance(term, URIRef) and any(str(term).startswith(ns) for ns in EXTERNAL_PREFIXES.values()):
                    external.add(str(term))
        rows.append({
            "module": module, "file": rel, "triples": len(g), "classes": len(classes), "object": len(obj), "datatype": len(dt),
            "deprecated": len(deprecated), "subclass": subclass, "restrictions": restrictions, "domains": domains, "ranges": ranges,
            "terms": len(set(classes + obj + dt)), "labels": labels, "definitions": definitions,
            "external": sorted(external),
        })
    return rows


def metrics_report(manifest: dict, ontology: Graph, module_rows: list[dict], shape_inv: dict) -> str:
    profile = load_yaml(ROOT / manifest["dist"]["profile"]) if (ROOT / manifest["dist"]["profile"]).suffix == ".yaml" else json.loads((ROOT / manifest["dist"]["profile"]).read_text(encoding="utf-8"))
    lines = [GENERATED, "# Ontology metrics (HCMO 0.3.0)\n"]
    lines.append("## Per module\n")
    table = []
    for r in module_rows:
        table.append([r["module"], r["classes"], r["object"], r["datatype"], r["deprecated"], r["subclass"], r["restrictions"], r["domains"] + r["ranges"], f"{r['labels']}/{r['terms']}", f"{r['definitions']}/{r['terms']}", r["triples"]])
    lines.append(md_table(["Module", "Classes", "Object props", "Datatype props", "Deprecated", "Named subClassOf", "Restrictions", "Domain+range axioms", "Labelled", "Defined", "Triples"], table))
    counts = profile["counts"]
    lines.append("\n## Merged release graph (`dist/`)\n")
    lines.append(md_table(["Metric", "Value"], [
        ["Triples", counts["triples"]],
        ["Declared classes (HCMO namespaces, incl. compatibility)", counts["classes"]],
        ["Object properties", counts["object_properties"]],
        ["Datatype properties", counts["datatype_properties"]],
        ["Annotation properties", counts["annotation_properties"]],
        ["Deprecated terms (all modules)", sum(r["deprecated"] for r in module_rows)],
        ["owl:Restriction axioms", sum(r["restrictions"] for r in module_rows)],
        ["External classes/properties referenced by axioms", len(set(t for r in module_rows for t in r["external"]))],
        ["SHACL node shapes / property shapes / SPARQL constraints", f"{shape_inv['node_shapes']} / {shape_inv['property_shapes']} / {shape_inv['sparql_constraints']}"],
    ]))
    lines.append("\n## Reused external terms per module\n")
    for r in module_rows:
        if r["external"]:
            lines.append(f"- **{r['module']}**: " + ", ".join(f"`{curie(t)}`" for t in r["external"]))
    lines.append("")
    return "\n".join(lines)


# ----------------------------------------------------------------- reasoner
def reasoner_report(manifest: dict) -> str:
    import owlready2.reasoning as owl_reasoning
    from owlready2 import default_world, get_ontology, sync_reasoner

    source = ROOT / manifest["dist"]["merged_owl"]
    owl_reasoning.JAVA_MEMORY = 2000
    onto = get_ontology(str(source.resolve())).load()
    asserted = {(c.iri, p.iri) for c in onto.classes() for p in c.is_a if hasattr(p, "iri")}
    sync_reasoner(debug=0)
    inferred = {(c.iri, p.iri) for c in onto.classes() for p in c.is_a if hasattr(p, "iri")}
    inconsistent = [c.iri for c in default_world.inconsistent_classes()]
    new_edges = sorted(inferred - asserted)
    lines = [GENERATED, "# Reasoner report (HermiT via owlready2)\n"]
    lines.append(md_table(["Metric", "Value"], [
        ["Source", f"`{source.relative_to(ROOT).as_posix()}`"],
        ["Loaded classes", len(list(onto.classes()))],
        ["Unsatisfiable / inconsistent classes", len(inconsistent)],
        ["Asserted named subclass edges", len(asserted)],
        ["Named subclass edges after classification", len(inferred)],
        ["Newly inferred named subclass edges", len(new_edges)],
    ]))
    if inconsistent:
        lines.append("\nInconsistent: " + ", ".join(inconsistent))
    if new_edges:
        lines.append("\n## Inferred edges not asserted in the sources\n")
        lines.append(md_table(["Subclass", "Superclass"], [[curie(a), curie(b)] for a, b in new_edges]))
    else:
        lines.append("\nClassification added no named subclass edge beyond those asserted: the inferred hierarchy equals the asserted hierarchy.\n")
    return "\n".join(lines)


# --------------------------------------------------------------------- driver
def load_system_graphs(index: dict) -> dict[str, Graph]:
    return {system["id"]: Graph().parse(ROOT / system["graph"], format="turtle") for system in index["systems"]}


def check_all(ontology: Graph) -> tuple[bool, list[str]]:
    """CI entry point: SHACL conformance + probes + exact cross-system CQs."""
    manifest = load_manifest()
    index = load_index()
    graphs = load_system_graphs(index)
    for system in index["systems"]:
        read_mapping(ROOT / system["mapping"])
    ok_shacl, notes, _ = shacl_evaluation(manifest, index, ontology, graphs)
    ok_cq, cq_notes, _ = cq_evaluation(index, evaluation_graph(ontology, graphs))
    return ok_shacl and ok_cq, notes + cq_notes


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--reason", action="store_true", help="also run HermiT and write reasoner.md (needs Java)")
    parser.add_argument("--print-answers", action="store_true", help="print current CQ result rows as YAML and exit")
    args = parser.parse_args()

    manifest = load_manifest()
    index = load_index()
    ontology = ontology_graph(manifest)
    graphs = load_system_graphs(index)
    union = evaluation_graph(ontology, graphs)

    if args.print_answers:
        cq_index = load_yaml(ROOT / index["queries"]["index"])
        for question in cq_index["questions"]:
            rows = canonical_rows(union.query((ROOT / question["file"]).read_text(encoding="utf-8")))
            print(f"# {question['id']}: {len(rows)} rows")
            print(yaml.safe_dump({"expected_answers": rows}, sort_keys=False, allow_unicode=True))
        return 0

    reports = index["reports"]
    write_text(ROOT / reports["coverage"], coverage_report(index, graphs))
    ok_shacl, notes, shacl_results = shacl_evaluation(manifest, index, ontology, graphs)
    write_text(ROOT / reports["shacl"], shacl_report(shacl_results))
    ok_cq, cq_notes, cq_results = cq_evaluation(index, union)
    write_text(ROOT / reports["competency"], cq_report(cq_results, union))
    write_text(ROOT / reports["metrics"], metrics_report(manifest, ontology, module_metrics(manifest), shacl_results["inventory"]))
    if args.reason:
        write_text(ROOT / "evaluation" / "reports" / "reasoner.md", reasoner_report(manifest))
    print("\n".join(notes + cq_notes))
    print(f"result: {'PASS' if ok_shacl and ok_cq else 'FAIL'}")
    return 0 if ok_shacl and ok_cq else 1


if __name__ == "__main__":
    raise SystemExit(main())
