#!/usr/bin/env python3
"""Generate the HCMO SKOS vendor/system schemes and the contribution-form options.

Sources and outputs:

- docs/hcm-systems/CATALOG.md (the two HCM system tables)
    -> vocabularies/vendors.ttl, vocabularies/systems.ttl
- vocabularies/file-formats.ttl and vocabularies/data-access-methods.ttl
  (their ``form-options`` ordered collections)
    -> the generated chip blocks in docs/hcm-systems/contribute/index.html

Concept IRIs are minted once and never re-minted: generation fails if a concept
IRI present in the current output would disappear. Deprecate it instead.

Usage:
    python tooling/export_hcm_vocab.py          # write outputs
    python tooling/export_hcm_vocab.py --check  # exit 1 if outputs are stale
"""
from __future__ import annotations

import argparse
import html
import re
import sys
from pathlib import Path

from rdflib import RDF, Graph, Literal, Namespace, URIRef
from rdflib.collection import Collection
from rdflib.namespace import DCTERMS, SKOS

sys.path.insert(0, str(Path(__file__).resolve().parent))
from export_hcm_catalog import clean_markdown, slugify, table_rows  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
CATALOG = ROOT / "docs" / "hcm-systems" / "CATALOG.md"
VOCAB_DIR = ROOT / "vocabularies"
VENDORS_OUT = VOCAB_DIR / "vendors.ttl"
SYSTEMS_OUT = VOCAB_DIR / "systems.ttl"
FILE_FORMATS = VOCAB_DIR / "file-formats.ttl"
ACCESS_METHODS = VOCAB_DIR / "data-access-methods.ttl"
FORM = ROOT / "docs" / "hcm-systems" / "contribute" / "index.html"

VENDOR_SCHEME = URIRef("https://w3id.org/hcmo/id/vocab/vendor")
SYSTEM_SCHEME = URIRef("https://w3id.org/hcmo/id/vocab/system")
VENDOR = Namespace("https://w3id.org/hcmo/id/vocab/vendor/")
SYSTEM = Namespace("https://w3id.org/hcmo/id/vocab/system/")
CATALOG_URL = URIRef("https://github.com/dhuzard/HCMO/blob/main/docs/hcm-systems/CATALOG.md")
LICENSE = URIRef("https://creativecommons.org/licenses/by/4.0/")

SYSTEM_SECTIONS = {
    "Commercial HCM platforms": ("commercial", "Commercial HCM platforms"),
    "Open-source / DIY systems": ("open-source", "Open-source and DIY HCM systems"),
}
SHORT_NAMES_SECTION = "System short names"
NO_VENDOR = {"", "—", "-"}
LEGAL_SUFFIX = re.compile(
    r"[,\s]+(S\.p\.A\.|Inc\.?|GmbH|Ltd\.?|AG|B\.V\.|LLC|S\.A\.S\.?|S\.A\.)$", re.IGNORECASE
)
FORM_BLOCKS = {
    "formats": FILE_FORMATS,
    "accessMethods": ACCESS_METHODS,
}


def header(title: str) -> str:
    return (
        f"# {title}\n"
        "# DO NOT EDIT BY HAND - generated by tooling/export_hcm_vocab.py from\n"
        "# docs/hcm-systems/CATALOG.md. Not part of the HCMO release manifest.\n"
    )


def vendor_names(cell: str) -> list[str]:
    return [name.strip() for name in cell.split(";") if name.strip() not in NO_VENDOR]


def vendor_slug(name: str) -> tuple[str, str | None]:
    """Return the IRI slug and an abbreviation given in parentheses, if any."""
    abbreviation = None
    match = re.search(r"\(([^)]+)\)\s*$", name)
    base = name
    if match:
        abbreviation = match.group(1).strip()
        base = name[: match.start()].strip()
    base = LEGAL_SUFFIX.sub("", base).strip()
    return slugify(base), abbreviation


def system_slug(row: dict[str, str], name: str) -> str:
    slug = row.get("slug") or ""
    return slugify(slug.rsplit("/", 1)[-1]) if slug else slugify(name)


def scheme(g: Graph, iri: URIRef, title: str, description: str) -> None:
    g.add((iri, RDF.type, SKOS.ConceptScheme))
    g.add((iri, DCTERMS.title, Literal(title, lang="en")))
    g.add((iri, DCTERMS.description, Literal(description, lang="en")))
    g.add((iri, DCTERMS.license, LICENSE))
    g.add((iri, DCTERMS.source, CATALOG_URL))


def build_catalog_graphs() -> tuple[Graph, Graph]:
    vendors, systems = Graph(), Graph()
    for g in (vendors, systems):
        g.bind("skos", SKOS)
        g.bind("dcterms", DCTERMS)
        g.bind("vendor", VENDOR)
        g.bind("sys", SYSTEM)
    scheme(vendors, VENDOR_SCHEME, "HCMO vendor vocabulary",
           "Organisations that build or sell home-cage monitoring systems.")
    scheme(systems, SYSTEM_SCHEME, "HCMO system vocabulary",
           "Home-cage monitoring systems, commercial and open-source.")

    for key, (collection_slug, label) in SYSTEM_SECTIONS.items():
        collection = SYSTEM[collection_slug]
        systems.add((collection, RDF.type, SKOS.Collection))
        systems.add((collection, SKOS.prefLabel, Literal(label, lang="en")))

    markdown = CATALOG.read_text(encoding="utf-8")
    for row in table_rows(markdown):
        section = row.get("_section", "")
        if section not in SYSTEM_SECTIONS:
            continue
        name = row.get("System", "")
        if not name:
            continue
        slug = system_slug(row, name)
        concept = SYSTEM[slug]
        systems.add((concept, RDF.type, SKOS.Concept))
        systems.add((concept, SKOS.inScheme, SYSTEM_SCHEME))
        systems.add((concept, SKOS.topConceptOf, SYSTEM_SCHEME))
        systems.add((SYSTEM_SCHEME, SKOS.hasTopConcept, concept))
        systems.add((concept, SKOS.prefLabel, Literal(name, lang="en")))
        systems.add((concept, SKOS.notation, Literal(slug)))
        systems.add((concept, DCTERMS.source, CATALOG_URL))
        systems.add((SYSTEM[SYSTEM_SECTIONS[section][0]], SKOS.member, concept))
        if row.get("Modality"):
            systems.add((concept, SKOS.scopeNote, Literal(f"Modality: {row['Modality']}", lang="en")))
        if row.get("Authors") and row["Authors"] not in NO_VENDOR:
            systems.add((concept, SKOS.note, Literal(f"Authors: {row['Authors']}", lang="en")))

        for vendor_name in vendor_names(row.get("Vendor", "")):
            v_slug, abbreviation = vendor_slug(vendor_name)
            vendor = VENDOR[v_slug]
            vendors.add((vendor, RDF.type, SKOS.Concept))
            vendors.add((vendor, SKOS.inScheme, VENDOR_SCHEME))
            vendors.add((vendor, SKOS.topConceptOf, VENDOR_SCHEME))
            vendors.add((VENDOR_SCHEME, SKOS.hasTopConcept, vendor))
            vendors.add((vendor, SKOS.prefLabel, Literal(vendor_name, lang="en")))
            if abbreviation:
                vendors.add((vendor, SKOS.altLabel, Literal(abbreviation, lang="en")))
            vendors.add((vendor, DCTERMS.source, CATALOG_URL))
            # Cross-scheme links are recorded on both sides.
            vendors.add((vendor, SKOS.related, concept))
            systems.add((concept, SKOS.related, vendor))

    for row in table_rows(markdown):
        if row.get("_section") != SHORT_NAMES_SECTION:
            continue
        concept = SYSTEM[row.get("slug", "")]
        if (concept, RDF.type, SKOS.Concept) not in systems:
            raise SystemExit(f"[FAIL] short names given for unknown system slug {row.get('slug')!r}")
        for name in row.get("Short names", "").split(";"):
            if name.strip():
                systems.add((concept, SKOS.altLabel, Literal(name.strip(), lang="en")))

    for g in (vendors, systems):
        labels: dict[URIRef, set[str]] = {}
        for s, o in g.subject_objects(SKOS.prefLabel):
            labels.setdefault(s, set()).add(str(o))
        clashes = {str(s): sorted(v) for s, v in labels.items() if len(v) > 1}
        if clashes:
            raise SystemExit(f"[FAIL] one IRI minted from several labels: {clashes}")
    return vendors, systems


def serialize(g: Graph, title: str) -> str:
    return header(title) + g.serialize(format="turtle")


def read(path: Path) -> str:
    """Read UTF-8 text without newline translation."""
    return path.read_bytes().decode("utf-8")


def minted(path: Path) -> set[str]:
    if not path.exists():
        return set()
    g = Graph().parse(path, format="turtle")
    return {str(s) for s in g.subjects(RDF.type, SKOS.Concept)}


def form_options(path: Path) -> list[tuple[str, str, str]]:
    """Return (value, concept IRI, chip text) for each form option, in order."""
    g = Graph().parse(path, format="turtle")
    options_node = next(
        s for s in g.subjects(RDF.type, SKOS.OrderedCollection) if str(s).endswith("/form-options")
    )
    options = []
    for concept in Collection(g, g.value(options_node, SKOS.memberList)):
        pref = str(g.value(concept, SKOS.prefLabel))
        notation = g.value(concept, SKOS.notation)
        alts = sorted(str(a) for a in g.objects(concept, SKOS.altLabel))
        options.append((str(notation) if notation else pref, str(concept), alts[0] if alts else pref))
    return options


def render_form(text: str) -> str:
    for name, path in FORM_BLOCKS.items():
        begin = f"<!-- BEGIN generated {name} options: tooling/export_hcm_vocab.py -->"
        end = f"<!-- END generated {name} options -->"
        pattern = re.compile(r"([ \t]*)" + re.escape(begin) + r".*?" + re.escape(end), re.DOTALL)
        match = pattern.search(text)
        if not match:
            raise SystemExit(f"[FAIL] generated-block markers for {name!r} not found in {FORM}")
        indent = match.group(1)
        chips = [
            f'{indent}<label class="chip" title="{html.escape(value)}"><input type="checkbox" '
            f'name="{name}" value="{html.escape(value)}" data-concept="{html.escape(concept)}" /> '
            f"{html.escape(chip)}</label>"
            for value, concept, chip in form_options(path)
        ]
        block = "\n".join([indent + begin, *chips, indent + end])
        text = text[: match.start()] + block + text[match.end():]
    return text


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="fail if generated outputs are stale")
    parser.add_argument(
        "--allow-drop", nargs="+", default=[], metavar="IRI",
        help="concept IRIs that may disappear; only for IRIs never released",
    )
    args = parser.parse_args()

    vendors, systems = build_catalog_graphs()
    outputs = {
        VENDORS_OUT: serialize(vendors, "HCMO vendor vocabulary (SKOS)."),
        SYSTEMS_OUT: serialize(systems, "HCMO system vocabulary (SKOS)."),
    }
    form_raw = read(FORM)
    form_newline = "\r\n" if "\r\n" in form_raw else "\n"
    outputs[FORM] = render_form(form_raw.replace("\r\n", "\n"))

    dropped = sorted(
        (minted(VENDORS_OUT) | minted(SYSTEMS_OUT))
        - {str(s) for g in (vendors, systems) for s in g.subjects(RDF.type, SKOS.Concept)}
        - set(args.allow_drop)
    )
    if dropped:
        print(f"[FAIL] previously minted concept IRIs would disappear (deprecate instead): {dropped}")
        return 1

    stale = []
    for path, content in outputs.items():
        current = read(path).replace("\r\n", "\n") if path.exists() else None
        if current != content:
            stale.append(path)
            if not args.check:
                newline = form_newline if path == FORM else "\n"
                path.write_bytes(content.replace("\n", newline).encode("utf-8"))
    if args.check:
        for path in stale:
            print(f"[FAIL] stale generated output: {path.relative_to(ROOT)}")
        return 1 if stale else 0
    for path in outputs:
        status = "wrote" if path in stale else "unchanged"
        print(f"{status}: {path.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
